version: "3.3"

services:
  redis:
    image: redis:alpine
    restart: always

  api:
    image: scrap_flask:latest
    command: api
    ports:
      - 8000:8000
    expose:
      - 6379
    volumes:
      - type: bind
        source: ./app/
        target: /app/
    environment:
    - "PYTHONUNBUFFERED=0"
    - "TASKS_REDIS_URI=redis://redis:6379/0"
    restart: on-failure
    depends_on:
      - redis

  worker:
    image: scrap_flask:latest
    command: worker
    expose:
      - 6379
    volumes:
      - type: bind
        source: ./app/
        target: /app/
    environment:
    - "PYTHONUNBUFFERED=0"
    - "TASKS_REDIS_URI=redis://redis:6379/0"
    restart: on-failure
    depends_on:
      - redis
